# Generated by Django 5.1 on 2024-09-03 21:01

import utils.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danfe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danfe',
            name='arquivo_pdf',
            field=models.FileField(help_text='Arquivo PDF da DANFE', max_length=255, upload_to='pdf/%Y/%m', validators=[utils.model_validators.validate_pdf, utils.model_validators.validate_danfe], verbose_name='DANFE em PDF'),
        ),
        migrations.AlterField(
            model_name='danfe',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
