# Generated by Django 5.1 on 2024-09-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danfe', '0002_alter_danfe_arquivo_pdf_alter_danfe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danfe',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
