# Generated by Django 5.1 on 2024-09-04 13:14

import utils.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danfe', '0003_alter_danfe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danfe',
            name='arquivo_pdf',
            field=models.FileField(help_text='Arquivo PDF da DANFE', max_length=255, upload_to='pdf/%Y/%m', validators=[utils.model_validators.validate_danfe], verbose_name='DANFE em PDF'),
        ),
    ]
