services:
  danfeapp:
    container_name: danfeapp
    build:
      context: .
    ports:
      - 8080:8000  # Mapeia a porta 8080 do host para a porta 8000 do container
    volumes:
      - ./danfeapp:/danfeapp
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
      - mongodb

  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017  # Porta padrão do MongoDB
    volumes:
      - ./data/mongodb:/data/db
    env_file:
      - ./dotenv_files/.env  # Usa o mesmo arquivo .env para o MongoDB
